[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
  included_files = [
    "data/quest-seed.json",
    "data/ascension-blueprints.json",
    "data/ascension-blueprint-wallets.json"
  ]
