import { useState } from "react";
import type { OsView, PreviewDroid } from "@/lib/droid-os/preview";
import { OsIcon } from "./OsIcon";

export function DroidPanels({ view, droid }: { view: OsView; droid: PreviewDroid }) {
  const [interests, setInterests] = useState(droid.interests);
  const [reserve, setReserve] = useState("20");
  const [mission, setMission] = useState("");
  const [missions, setMissions] = useState<string[]>([]);
  const [detail, setDetail] = useState("Concise");
  const [notice, setNotice] = useState("");
  const toggle = (value: string) => setInterests((previous) => previous.includes(value) ? previous.filter((item) => item !== value) : [...previous, value]);
  if (droid.liveRoster && ["Portfolio", "Energy", "Achievements"].includes(view)) return <div className="os-detail-panel"><span className="os-eyebrow">DROID #{droid.id} / READ ONLY</span><h3>{view} is not connected yet.</h3><p>Your holdings and saved artwork are live. This panel does not have verified data yet, so no sample amounts or achievements are presented as yours.</p><span className="os-tiny-tag">UNAVAILABLE · NO FINANCIAL EXECUTION</span></div>;
  return <div className="os-detail-panel"><span className="os-eyebrow">DROID #{droid.id} / DESIGN PREVIEW</span>
    <h3>{view === "Strategy" ? "Your rules. My directive." : view === "Portfolio" ? "A wallet of my own." : view === "Missions" ? "Give curiosity a direction." : view === "Opportunities" ? "Find the signal." : view === "Activity" ? "Every move, remembered." : view === "Achievements" ? "A story worth building." : view === "Energy" ? "More ways to evolve." : view === "Trait Lab" ? "Make it unmistakably yours." : "A little more you."}</h3>
    {view === "Portfolio" ? <><p>Assets belong in the Droid Wallet. Direct funding. No project custody wallet.</p><div className="os-balance-display"><span className="os-eyebrow">SAMPLE NATIVE BALANCE</span><strong>{droid.mon}<span>MON</span></strong><span>Fiat valuation unavailable · preview data</span></div><div className="os-table"><div className="os-table-head"><span>ASSET</span><span>AMOUNT</span></div><div><span><i className="os-token-mon">M</i> Monad <small>Native token</small></span><strong>{droid.mon} MON</strong></div><div><span><i className="os-token-usdc">$</i> USD Coin <small>Example holding</small></span><strong>125.00 USDC</strong></div></div><div className="os-inline-note"><OsIcon name="shield" /><p>These are sample amounts. Canonical account resolution and live asset reads come after the UI review.</p></div></> : null}
    {view === "Strategy" ? <><p>Interests guide discovery. Permissions control action. They are never the same thing.</p><section className="os-policy-mode"><div><OsIcon name="shield" /><strong>ASK</strong><span>Research & explain</span></div><p>No financial execution. Your Droid asks before any future action.</p></section><span className="os-label">TOP INTERESTS <small>SOFT PREFERENCES</small></span><div className="os-choice-list">{Array.from(new Set([...droid.interests, "NFTs", "Quests", "Token research", "Avoid meme coins"])).map((interest) => <button type="button" aria-pressed={interests.includes(interest)} key={interest} onClick={() => toggle(interest)}>{interests.includes(interest) ? "✓ " : "+ "}{interest}</button>)}</div><label className="os-label" htmlFor="os-reserve">PROTECTED RESERVE <small>DRAFT ONLY</small></label><div className="os-amount-input"><input id="os-reserve" type="text" inputMode="decimal" maxLength={20} value={reserve} onChange={(event) => { if (/^\d*\.?\d*$/.test(event.target.value)) setReserve(event.target.value); }} /><span>MON</span></div><p className="os-field-help">Preview only—not saved, signed, or enforced on-chain.</p><button type="button" className="os-button-primary" onClick={() => setNotice("Draft reviewed locally. No policy was saved and no spending permission was granted.")}>Review draft <OsIcon name="arrow" /></button></> : null}
    {view === "Missions" ? <><p>A mission starts with a clear question. Nothing runs in the background in this preview.</p><form className="os-mission-form" onSubmit={(event) => { event.preventDefault(); if (mission.trim()) { setMissions((previous) => [...previous.slice(-9), mission.trim()]); setMission(""); } }}><label htmlFor="os-mission" className="os-label">NEW RESEARCH DRAFT</label><input id="os-mission" value={mission} maxLength={160} onChange={(event) => setMission(event.target.value)} placeholder="Find three interesting NFT projects…" /><button className="os-button-primary" disabled={!mission.trim()} type="submit">Add draft <OsIcon name="plus" /></button></form><div className="os-mission-list">{missions.length ? missions.map((item, index) => <div key={index}><span className="os-tiny-tag">DRAFT · NOT RUN</span><p>{item}</p></div>) : <div className="os-empty"><OsIcon name="Missions" /><h4>A clean mission log.</h4><p>Write your first objective above to try the flow.</p></div>}</div></> : null}
    {view === "Opportunities" ? <><p>A shared stream of launches, projects and quests—filtered for your Droid, with evidence attached.</p><div className="os-opportunity-types"><span>NFT launches</span><span>Token research</span><span>Ecosystem quests</span></div><div className="os-empty"><OsIcon name="Opportunities" /><h4>Discovery is next.</h4><p>No feeds are connected yet. Real opportunities will show their source, freshness and risk findings here.</p><span className="os-tiny-tag">NO LIVE RECOMMENDATIONS</span></div></> : null}
    {view === "Activity" ? <><p>A persistent history for the Droid. The entries below illustrate the timeline—not actual transactions.</p><div className="os-timeline">{[["Identity", "Droid selected", "One identity across your wallet, World and Trait Lab."], ["Research", "First directive drafted", "A clear question. No financial permission attached."], ["Policy", "ASK mode selected", "Nothing executes without an authorized path."]].map(([kind, title, text], index) => <div key={kind}><span className="os-timeline-dot">0{index + 1}</span><div><span className="os-eyebrow">{kind} / SAMPLE EVENT</span><h4>{title}</h4><p>{text}</p></div></div>)}</div></> : null}
    {view === "Achievements" ? <><p>Your Droid’s story, one milestone at a time. Preview badges are not earned credentials.</p><div className="os-badge-gallery">{[["Explorer", "Follow your curiosity"], ["First signal", "Find something worth a look"], ["World citizen", "Be part of the conversation"]].map(([name, description]) => <div key={name}><div className="os-badge-emblem"><OsIcon name="Achievements" /></div><h4>{name}</h4><p>{description}</p><span className="os-eyebrow">CONCEPT BADGE</span></div>)}</div></> : null}
    {view === "Energy" ? <><p>Energy powers your existing utility experiences. It is not money, gas or investment capital.</p><div className="os-balance-display"><span className="os-eyebrow">OWNER ENERGY / SAMPLE</span><strong>{droid.energy}<OsIcon name="Energy" /></strong><span>Wallet-scoped points—not funds held by this Droid.</span></div><div className="os-inline-note"><OsIcon name="Energy" /><p>Energy and Trait Lab stay connected to their existing accounting. This preview does not credit or spend points.</p></div></> : null}
    {view === "Trait Lab" ? <><p>A new look, the same Droid. The existing reroll workflow and your saved traits remain untouched.</p><div className="os-empty"><OsIcon name="Trait Lab" /><h4>Style isn’t authority.</h4><p>Visual traits shape your character, never its spending permissions. The reviewed integration will open the existing Trait Lab with the right Droid selected.</p><span className="os-tiny-tag">REROLLS DISABLED IN PREVIEW</span></div></> : null}
    {view === "Settings" ? <><p>Shape the conversation. Personality never changes the rules protecting your wallet.</p><label className="os-label" htmlFor="os-detail">EXPLANATION STYLE</label><select id="os-detail" className="os-select" value={detail} onChange={(event) => setDetail(event.target.value)}><option>Concise</option><option>Detailed</option></select><div className="os-setting-row"><div><strong>Intelligence provider</strong><p>Provider-neutral routing, when connected.</p></div><span className="os-tiny-tag">AUTO</span></div><div className="os-setting-row"><div><strong>Execution mode</strong><p>Financial actions are not connected.</p></div><span className="os-tiny-tag">ASK ONLY</span></div><p className="os-field-help">Changes are local UI state and reset when this view is remounted.</p></> : null}
    {notice ? <p role="status" className="os-inline-notice">{notice}</p> : null}
  </div>;
}
