"use client";

import { useEffect, useRef, useState } from "react";
import { OS_VIEWS, PREVIEW_DROIDS, type OsView, type PreviewDroid } from "@/lib/droid-os/preview";
import { DroidCharacter } from "./DroidCharacter";
import { DroidTalk } from "./DroidTalk";
import { DroidPanels } from "./DroidPanels";
import { OsIcon } from "./OsIcon";
import { DroidLiveWalletStatus } from "./DroidLiveWalletStatus";
import { DroidAskWorkspace } from "./DroidAskWorkspace";
import type { AskClient } from "@/hooks/useDroidAskClient";

function CustodyPreview({ action, close }: { action: "Fund" | "Withdraw"; close: () => void }) {
  const dialog = useRef<HTMLDialogElement>(null);
  useEffect(() => { const element = dialog.current; element?.showModal(); return () => element?.close(); }, []);
  return <dialog className="os-custody-dialog" ref={dialog} aria-labelledby="os-custody-title" onCancel={close} onClick={(event) => { if (event.target === event.currentTarget) close(); }}><div className="os-dialog-top"><span className="os-eyebrow">OWNER CONTROLLED</span><button type="button" aria-label="Close wallet preview" onClick={close}><OsIcon name="close" /></button></div><div className="os-dialog-symbol"><OsIcon name="Portfolio" /></div><h2 id="os-custody-title">{action} your Droid.</h2><p>{action === "Fund" ? "Funds will go directly from your wallet to this Droid’s verified canonical account. Never through a project wallet." : "Withdrawals will require the current NFT owner’s explicit authorization and a verified destination. AI will not have withdrawal authority."}</p><div className="os-custody-flow"><span>{action === "Fund" ? "OWNER WALLET" : "DROID WALLET"}</span><OsIcon name="arrow" /><span>{action === "Fund" ? "DROID WALLET" : "OWNER DESTINATION"}</span></div><div className="os-inline-note"><OsIcon name="shield" /><p>No wallet is connected in this review. No address, payment or signing request will be generated.</p></div><button className="os-button-primary" type="button" onClick={close}>Back to my Droid <OsIcon name="arrow" /></button></dialog>;
}

export function DroidOsPreview({ roster = PREVIEW_DROIDS, askClient }: { roster?: readonly PreviewDroid[]; askClient?: AskClient }) {
  const [selectedId, setSelectedId] = useState("11");
  const [view, setView] = useState<OsView>("Talk");
  const [custody, setCustody] = useState<"Fund" | "Withdraw" | null>(null);
  const [mobileWorkspace, setMobileWorkspace] = useState(false);
  const droid = roster.find((item) => item.id === selectedId) || roster[0];
  function navigate(next: OsView) { setView(next); setMobileWorkspace(true); }
  function select(id: string) { setSelectedId(id); }

  return <div className={`droid-os os-shell ${mobileWorkspace ? "os-mobile-workspace" : ""}`}>
    <a className="os-skip-link" href="#os-workspace">Skip to workspace</a>
    <div className="os-preview-bar"><span><i /> {droid.liveRoster ? "LIVE ROSTER · ASK CANARY" : "UI REVIEW · DEMO"}</span><p>{droid.liveRoster ? "Real holdings & artwork. Owner-signed training. AI requires setup. Portfolio unavailable. No execution." : "Sample roster & balances. Connect above for your holdings. No live AI or transactions."}</p><span>BUILD 0.3</span></div>
    <header className="os-header"><a href="https://dyoor.fun" className="os-wordmark" aria-label="DYOOR main site">DYØØR<span>.</span></a><div className="os-product-name"><span>DROID OS</span><small>YOUR DROID. YOUR DIRECTIVE.</small></div><div className="os-header-status"><span className="os-chain-mark">◇</span><span>MONAD <small>143</small></span><span className="os-header-divider" /><span className="os-owner-state">{droid.liveRoster ? "READ-ONLY CONNECTION" : "WALLET NOT CONNECTED"}</span></div>{droid.liveRoster ? <span className="os-tiny-tag">CUSTODY NOT CONNECTED</span> : <button className="os-header-button" type="button" onClick={() => setCustody("Fund")}><OsIcon name="Portfolio" /><span>Wallet preview</span></button>}</header>
    <nav className="os-mobile-nav" aria-label="Mobile Droid navigation"><button type="button" aria-current={!mobileWorkspace ? "page" : undefined} onClick={() => { setMobileWorkspace(false); window.scrollTo({ top: 0, behavior: "auto" }); }}><OsIcon name="grid" />Droid</button>{(["Talk", "Portfolio", "Strategy"] as const).map((item) => <button key={item} type="button" aria-current={mobileWorkspace && view === item ? "page" : undefined} onClick={() => { navigate(item); window.scrollTo({ top: 0, behavior: "auto" }); }}><OsIcon name={item} />{item}</button>)}<label className="os-mobile-more"><OsIcon name="grid" /><span>More</span><select aria-label="More Droid sections" value="" onChange={(event) => { navigate(event.target.value as OsView); window.scrollTo({ top: 0, behavior: "auto" }); }}><option value="" disabled>Choose a section</option>{OS_VIEWS.filter((item) => !["Talk", "Portfolio", "Strategy"].includes(item)).map((item) => <option value={item} key={item}>{item}</option>)}</select></label></nav>
    <div className="os-body"><aside className="os-rail"><button type="button" className="os-rail-home" aria-label="Show Droid selection" onClick={() => { setMobileWorkspace(false); document.getElementById("os-droid-heading")?.scrollIntoView({ behavior: "auto" }); }}><OsIcon name="grid" /></button><div className="os-rail-line" /><nav aria-label="Droid OS sections">{OS_VIEWS.map((item) => <button key={item} type="button" title={item} aria-label={item} aria-current={view === item ? "page" : undefined} className={view === item ? "os-rail-active" : ""} onClick={() => navigate(item)}><OsIcon name={item} /><span>{item}</span></button>)}</nav><a className="os-world-link" href="https://dyoor.fun/dyoor-world" target="_blank" rel="noreferrer" aria-label="Open dYOOR World"><OsIcon name="world" /><span>World ↗</span></a></aside>
      <main className="os-main"><div className="os-page-heading"><div><span className="os-eyebrow"><span className="os-cyan">DROID CONTROL CENTER</span> / SEASON 02</span><h1 id="os-droid-heading">Select your Droid<span>.</span></h1><p>Not just a collectible. A character with a purpose.</p></div><div className="os-system-note"><span className="os-orbit-icon" aria-hidden="true">◎</span><div><span>INTELLIGENCE, BOUNDED.</span><p>You remain in control.</p></div></div></div>
        <div className="os-main-grid"><DroidCharacter droid={droid} select={select} roster={roster} /><section className="os-workspace" id="os-workspace" tabIndex={-1} aria-label={`${view} workspace`}><div className="os-workspace-heading"><div><OsIcon name={view} /><h2>{view}</h2></div><span>DROID #{droid.id}<i /></span></div><nav className="os-workspace-tabs" aria-label="Workspace views">{(["Talk", "Portfolio", "Strategy", "Missions", "Activity"] as const).map((item) => <button key={item} type="button" aria-pressed={view === item} onClick={() => navigate(item)}>{item}</button>)}</nav>{droid.liveRoster && askClient ? <DroidAskWorkspace key={droid.id} view={view} droid={droid} client={askClient} /> : view === "Talk" ? <DroidTalk key={`talk-${droid.id}`} droid={droid} /> : <DroidPanels key={`${droid.id}-${view}`} view={view} droid={droid} />}</section></div>
        {droid.liveRoster ? <DroidLiveWalletStatus /> : <section className="os-wallet-strip" aria-label="Sample Droid status"><div className="os-wallet-identity"><span className="os-eyebrow"><OsIcon name="Portfolio" /> DROID WALLET</span><strong>Attached to the Droid.</strong><span>Canonical address pending connection</span></div><div className="os-wallet-metric"><span className="os-eyebrow">MON BALANCE <i>DEMO</i></span><strong>{droid.mon}<small>MON</small></strong></div><button className="os-wallet-metric os-metric-button" type="button" onClick={() => navigate("Energy")}><span className="os-eyebrow">OWNER ENERGY <i>DEMO</i></span><strong>{droid.energy}<OsIcon name="Energy" /></strong></button><button className="os-wallet-metric os-metric-button" type="button" onClick={() => navigate("Achievements")}><span className="os-eyebrow">ACHIEVEMENTS <i>DEMO</i></span><strong>{droid.achievements}<OsIcon name="Achievements" /></strong></button><div className="os-wallet-actions"><button className="os-button-primary" type="button" onClick={() => setCustody("Fund")}><OsIcon name="plus" /> Fund Droid</button><button className="os-button-secondary" type="button" onClick={() => setCustody("Withdraw")}>Withdraw <span>↗</span></button></div></section>}
        <footer className="os-footer"><span>DIRECTIVE: YIELD OPPORTUNITY OPTIMIZATION ROBOTS</span><span><OsIcon name="shield" /> Owner funded. Protocol bounded. Droid held.</span></footer>
      </main></div>
    {custody ? <CustodyPreview action={custody} close={() => setCustody(null)} /> : null}
  </div>;
}
