export const DYOOR_BUILDER_LAYER_ORDER = [
  "Background",
  "Droid",
  "Condition",
  "Eyes",
  "Clothes",
  "Mouth",
  "Special",
  "Hat",
  "Accessories",
  "Accessories 2"
];

export const DYOOR_BUILDER_RANDOMIZER = {
  requiredCategories: ["Background", "Droid", "Eyes", "Mouth"],
  optionalCategoryChances: {
    Condition: 0.35,
    Clothes: 0.78,
    Hat: 0.42,
    Accessories: 0.22,
    "Accessories 2": 0.22,
    Special: 0.08
  }
};

// Public builder traits. Includes every local PNG in /dyoor-builder/layers/{Category}.
// iCloud placeholder files are intentionally excluded because the browser cannot load them.
export const DYOOR_BUILDER_TRAITS = {
  Background: [
    "Goldish.PNG",
    "Grey.PNG",
    "Hawhyte.PNG",
    "Kewl.PNG",
    "Kinda Blue.PNG",
    "Pank.PNG",
    "Sunset.PNG",
    "Yorange.PNG"
  ],
  Droid: [
    "Black.png",
    "Blue.png",
    "Gold Chrome.png",
    "Gold.png",
    "Green.png",
    "Lime Green.png",
    "Olive Chrome.png",
    "Olive.png",
    "Optimus (T3SLA Bot).png",
    "Orange.png",
    "Purple.png",
    "Red.png",
    "White.png",
    "Whyte Chrome.png",
    "Yellow.png"
  ],
  Condition: [
    "Dirty-Broken.png",
    "DYOOR Chest Tat.png",
    "S1 Skin.png"
  ],
  Eyes: [
    "Abyss Laser.png",
    "Abyss.png",
    "Build Anything Glasses.png",
    "Cyclops.png",
    "Excited.png",
    "Eye Patch.png",
    "Googley Eyes.png",
    "Got em.png",
    "HMMMHM.png",
    "I Know What You Did.png",
    "Lazy Laser.png",
    "Monad Specs Black.png",
    "Monad Specs Gold.png",
    "Neverland Specs.png",
    "Okay.png",
    "Point Dexter Glasses Eyes.png",
    "Radiation Glow (Red).png",
    "Radiation Glow (Red)Laser.png",
    "Radiation Glow.png",
    "Ricky V.png",
    "Sly.png",
    "Snake Eyes.png",
    "Sunglasses.png",
    "Third Eye.png",
    "Tri-Specs.png",
    "Un Enthused.png",
    "VR Headset.png",
    "Zombie.png"
  ],
  Mouth: [
    "AHHH Tongue.png",
    "AHHHH Flames.png",
    "AHHHH.png",
    "Ayeee.png",
    "Ayeyo.png",
    "Braces.png",
    "Cigar Mouth.png",
    "Deep Thought.png",
    "Displeased toothpick.png",
    "Displeased.png",
    "Drool.png",
    "Gold Bar.png",
    "Gold Grill.png",
    "Joint Mouth.png",
    "Meh Cigarette.png",
    "Meh.png",
    "MMMMKay.png",
    "Muah.png",
    "Party Horn Mouth.png",
    "Pepe Mouth.png",
    "Pipe.png",
    "Resting DYOOR mouth.png",
    "Toothless Drool.png",
    "Vamp Fangs.png",
    "Waaaat.png"
  ],
  Clothes: [
    "Baby Blue Tee.png",
    "Beige Hoodie.png",
    "Black Hoodie.png",
    "Black N White Tee 2.png",
    "Black N White Tee.png",
    "Black Racer.png",
    "Black Tee 2.png",
    "Black Tee.png",
    "Blue Hoodie.png",
    "Blue Racer.png",
    "Caveman Leotard.png",
    "Convict Shirt.png",
    "Dictator Jacket.png",
    "DWO Black 2.png",
    "DWO Black.png",
    "DWO White.png",
    "DYOOR Black Hoodie.png",
    "Fur Coat Gold.png",
    "Fur Coat Pink.png",
    "Fur Coat Purple.png",
    "Grey Hoodie.png",
    "Grey Racer.png",
    "Grey Tee.png",
    "Hawaiian Shirt 2.png",
    "Jailhouse Stripes Shirt.png",
    "King's Robe 2.png",
    "King's Robe.png",
    "Kuru Tee.png",
    "Lab Coat 2.png",
    "Lab Coat.png",
    "Leather Jacket Torn Tee 2.png",
    "Leather Jacket Torn Tee.png",
    "Leather Jacket White Shirt W:Tie.png",
    "Leather Jacket.png",
    "Luffy.png",
    "McDyoornalds.png",
    "Neverland Tee.png",
    "Orange Plaid.png",
    "Orange Racer 2.png",
    "Orange Racer.png",
    "Overalls.png",
    "PAMPAM Tee.png",
    "Pink Plaid.png",
    "Red Hoodie 2.png",
    "Red Hoodie.png",
    "Red Plaid.png",
    "Tech Bro.png",
    "Torn Black Tee.png",
    "Torn Tee 2.png",
    "Torn Tee.png",
    "Tuxedo 2.png",
    "Tuxedo.png",
    "White Shirt W:Tie.png",
    "White Tee 2.png",
    "White Tee.png"
  ],
  Hat: [
    "Antenna.png",
    "Beanie Red.png",
    "Black Ball Cap.png",
    "Black Beanie.png",
    "Black Cap.png",
    "Black N White Cap.png",
    "Black Shystie.png",
    "BOB Mask.png",
    "Captain Hat.png",
    "Construction.png",
    "Cowboy.png",
    "Crown.png",
    "Dunce Hat.png",
    "DWO Black Cap.png",
    "DYOOR Black Cap.png",
    "DYOOR Flipped Brim.png",
    "DYOOR White Cap.png",
    "Glowing Antenna.png",
    "Gotta Catchem Cap.png",
    "Halo.png",
    "Horns.png",
    "Jailhouse Stripes Hat.png",
    "Luffy.png",
    "McDYOORs.png",
    "Monad Cap Black.png",
    "Monad Cap.png",
    "Party Hat.png",
    "Pink Shystie.png",
    "Pirate Hat.png",
    "Sweatband.png",
    "Tech bro.png",
    "Wormhole.png"
  ],
  Accessories: [
    "Bandaid.png",
    "Bandana Black.png",
    "Bandana Pink.png",
    "BOB-chain.png",
    "Choker Necklace.png",
    "Molandak.png"
  ],
  "Accessories 2": [
    "Bandaid.png",
    "Bandana Black.png",
    "Bandana Pink.png",
    "BOB-chain.png",
    "Choker Necklace.png",
    "Molandak.png"
  ],
  Special: [
    "Anime Mask.png",
    "Gimp.png",
    "Green Ski Mask Laser.png",
    "Pink Ski Mask Laser.png",
    "Space Suit.png"
  ]
};
