import type { ProjectConfig } from "../src/discord/model.js";

const none = 0n;

export const dyoorDiscordConfig = {
  name: "DYØØR",
  description:
    "The official DYØØR network for Season 1, Ascension, Season 2, HoodYØØR, Energy, and on-chain droid culture.",
  expected: {
    applicationId: "1488722061038715101",
    guildId: "1462783318004338837",
    ownerId: "1164591872396775508",
    guildName: "DYOOR",
  },
  roles: [
    {
      key: "dyoorified",
      name: "DYOORyfied",
      existingId: "1463877305171710063",
      aliases: ["DYØØRified", "DYOORified"],
      color: 0xa84400,
      hoist: false,
      mentionable: false,
      permissions: none,
    },
    {
      key: "season1",
      name: "DYOOR HODLER",
      existingId: "1463876633743200342",
      aliases: ["Season 1 Holder"],
      color: 0x9b5656,
      hoist: true,
      mentionable: false,
      permissions: none,
    },
    {
      key: "ascended",
      name: "Ascended",
      existingId: "1463876629544701992",
      color: 0xf1c40f,
      hoist: true,
      mentionable: false,
      permissions: none,
    },
    {
      key: "season2",
      name: "Season 2 Holder",
      color: 0x25e3a6,
      hoist: true,
      mentionable: false,
      permissions: none,
    },
    {
      key: "hoodyoor",
      name: "HoodYØØR",
      color: 0x00c805,
      hoist: true,
      mentionable: false,
      permissions: none,
    },
  ],
  staffRoles: [
    {
      key: "founder",
      name: "DYOOR FOUNDER",
      existingId: "1464219213064306792",
    },
    { key: "admin", name: "Admin", existingId: "1463876628190068736" },
    { key: "moderator", name: "DYOOR Mod", existingId: "1463876628747784212" },
    { key: "staff", name: "DYOOR STAFF", existingId: "1463876618903752889" },
  ],
  categories: [
    {
      key: "start-here",
      name: "── ⋆⋅☆⋅⋆ ── DYOOR ── ⋆⋅☆⋅⋆ ──",
      existingId: "1463886538684502199",
      channels: [
        {
          key: "welcome",
          name: "👋-welcome",
          existingId: "1462973299192758313",
          aliases: ["welcome"],
          type: "text",
          access: "entry-readonly",
          topic: "Begin here: the official DYØØR entry point and security orientation.",
          panel: "welcome",
        },
        {
          key: "rules",
          name: "👮「✦-rules-✦」",
          existingId: "1462972529965666356",
          aliases: ["rules"],
          type: "text",
          access: "entry-readonly",
          topic: "DYØØR community rules and wallet-safety requirements.",
          panel: "rules",
        },
        {
          key: "official-links",
          name: "🔗「✦-official-links-✦」",
          existingId: "1463886920080687258",
          aliases: ["official-links"],
          type: "text",
          access: "entry-readonly",
          topic: "The authoritative DYØØR links and contract registry.",
          panel: "security",
        },
        {
          key: "basic-verification",
          name: "🔐verify",
          existingId: "1463883574876045525",
          aliases: ["verify"],
          type: "text",
          access: "entry-verification",
          topic:
            "Complete Discord verification here. Wallet verification never requests a transaction or approval.",
        },
        {
          key: "announcements",
          name: "📢「✦-major-announcements-✦」",
          existingId: "1462971800056234093",
          aliases: ["announcements"],
          type: "text",
          access: "dyoorified-readonly",
          topic: "Official DYØØR announcements.",
        },
        {
          key: "sales",
          name: "sales-listings",
          existingId: "1475119645743648789",
          aliases: ["sales"],
          type: "text",
          access: "sales-readonly",
          topic: "Validated Season 1 and Season 2 marketplace sales. Bot-posted and deduplicated.",
        },
      ],
    },
    {
      key: "community",
      name: "── ⋆⋅☆⋅⋆ ── LOUNGE ── ⋆⋅☆⋅⋆ ──",
      existingId: "1462783319979593750",
      channels: [
        {
          key: "waiting-room",
          name: "waiting-room",
          existingId: "1462783319979593752",
          aliases: ["💬「✦-general-chat-✦」", "general-chat"],
          type: "text",
          access: "dyoorified-chat",
          slowmodeSeconds: 3,
          topic:
            "The public DYØØR hub for verified members, questions, community, and wallet sync.",
          panel: "waiting-room",
        },
        {
          key: "season1-ascended",
          name: "🔐「✦-dyoor-holders-✦」",
          existingId: "1475482197413728367",
          aliases: ["s1-ascended", "dyoor-holders"],
          type: "text",
          access: "season1-ascended-chat",
          slowmodeSeconds: 3,
          topic: "Combined private chat for Season 1 holders or currently Ascended members.",
        },
        {
          key: "season2-holders",
          name: "season-2-holders",
          type: "text",
          access: "season2-chat",
          slowmodeSeconds: 3,
          topic: "Season 2 droids, traits, rerolls, burns, Energy, and collection strategy.",
        },
        {
          key: "hoodyoor",
          name: "hoodyoor",
          type: "text",
          access: "hoodyoor-chat",
          slowmodeSeconds: 3,
          topic: "Private HoodYØØR holder access on Robinhood Chain.",
        },
      ],
    },
    {
      key: "support",
      name: "── ⋆⋅☆⋅⋆ ── SUPPORT ── ⋆⋅☆⋅⋆ ──",
      existingId: "1463879395906293821",
      channels: [
        {
          key: "open-a-ticket",
          name: "🎟️「✦-create-a-ticket-✦」",
          existingId: "1463879461106880512",
          aliases: ["open-a-ticket", "create-a-ticket"],
          type: "text",
          access: "ticket-panel",
          topic: "Private DYØØR support. Staff never need wallet secrets.",
          panel: "tickets",
        },
      ],
    },
    {
      key: "staff",
      name: "── ⋆⋅☆⋅⋆ ── TEAM ONLY ── ⋆⋅☆⋅⋆ ──",
      existingId: "1463876440641765564",
      channels: [
        {
          key: "staff-chat",
          name: "👩‍🔧「✦-team-chat-✦」",
          existingId: "1466130199878828082",
          aliases: ["staff-chat", "team-chat"],
          type: "text",
          access: "staff-chat",
        },
        {
          key: "verification-log",
          name: "verification-log",
          type: "text",
          access: "staff-readonly",
        },
        { key: "moderation-log", name: "moderation-log", type: "text", access: "staff-readonly" },
        { key: "ticket-log", name: "ticket-log", type: "text", access: "staff-readonly" },
        { key: "bot-log", name: "bot-log", type: "text", access: "staff-readonly" },
        { key: "security-alerts", name: "security-alerts", type: "text", access: "staff-readonly" },
      ],
    },
  ],
  chains: [
    {
      key: "monad",
      name: "Monad Mainnet",
      id: 143,
      currency: "MON",
      explorer: "https://monadscan.com",
      defaultRpcUrl: "https://rpc.monad.xyz",
      rpcEnvKey: "MONAD_RPC_URL",
    },
    {
      key: "robinhood",
      name: "Robinhood Chain",
      id: 4663,
      currency: "ETH",
      explorer: "https://robinhoodchain.blockscout.com",
      defaultRpcUrl: "https://rpc.mainnet.chain.robinhood.com",
      rpcEnvKey: "ROBINHOOD_RPC_URL",
    },
  ],
  contracts: [
    {
      key: "season1",
      label: "Season 1",
      chainKey: "monad",
      address: "0x2c79c9e233fea4b4dcfe6561d9209dc292cd932f",
      standard: "ERC721",
      expectedName: "DYOOR",
      expectedSymbol: "DYOOR",
      ownershipMethod: "balanceOf",
    },
    {
      key: "ascended",
      label: "Ascended",
      chainKey: "monad",
      address: "0xf9611226c1ccccca37951938d6f358d3d5106549",
      standard: "ASCENSION",
      ownershipMethod: "tokensOfStaker",
    },
    {
      key: "season2",
      label: "Season 2",
      chainKey: "monad",
      address: "0x349d8eb480c92cf75371fba5c6344a4d11b9103a",
      standard: "ERC721",
      expectedName: "D.Y.O.O.R",
      expectedSymbol: "DYOOR",
      ownershipMethod: "balanceOf",
    },
    {
      key: "hoodyoor",
      label: "HoodYØØR",
      chainKey: "robinhood",
      address: "0x8277f8126722b11d7b44c5c453bcf62a78aafa25",
      standard: "ERC721",
      expectedName: "HoodYØØR",
      expectedSymbol: "HOOD",
      ownershipMethod: "balanceOf",
    },
  ],
  salesCollections: [
    {
      key: "season1",
      label: "SEASON 1",
      chainKey: "monad",
      address: "0x2c79c9e233fea4b4dcfe6561d9209dc292cd932f",
    },
    {
      key: "season2",
      label: "SEASON 2",
      chainKey: "monad",
      address: "0x349d8eb480c92cf75371fba5c6344a4d11b9103a",
    },
  ],
  scheduledEvents: [],
  automodRules: [
    {
      key: "wallet-safety",
      name: "DYØØR · Wallet safety",
      kind: "keyword",
      keywords: [
        "*seed phrase*",
        "*recovery phrase*",
        "*private key*",
        "*wallet validation*",
        "*wallet rectification*",
        "*rectify wallet*",
        "*setapprovalforall*",
        "*connect wallet to claim*",
        "*support in dm*",
      ],
      blockMessage:
        "Possible wallet scam blocked. Use only links published inside official DYØØR channels.",
    },
    {
      key: "invite-review",
      name: "DYØØR · Invite review",
      kind: "keyword",
      keywords: ["*discord.gg/*", "*discord.com/invite/*"],
      blockMessage: "Unapproved Discord invites require staff review.",
    },
    {
      key: "mention-protection",
      name: "Block Mention Spam",
      kind: "mention-spam",
      mentionLimit: 5,
      blockMessage: "Too many mentions. Slow down and keep the network readable.",
    },
    {
      key: "spam-content",
      name: "DYØØR · Spam protection",
      kind: "spam",
      blockMessage: "Discord detected this message as spam.",
    },
  ],
  sync: {
    recheckIntervalHours: 6,
    gracePeriodHours: 24,
    concurrency: 4,
    rpcTimeoutMs: 10_000,
  },
  officialDomains: [
    "dyoor.xyz",
    "discord.com",
    "discord.gg",
    "opensea.io",
    "monadscan.com",
    "robinhoodchain.blockscout.com",
  ],
  copy: {
    welcome: {
      title: "DYØØR NETWORK — ENTRY PROTOCOL",
      body: "Read the rules, complete Discord verification, and receive DYOORyfied access. Wallet verification is optional, gas-free, and unlocks every holder area you qualify for.",
    },
    rules: {
      title: "DYØØR SECURITY PROTOCOL",
      rules: [
        "Respect members. No harassment, hate speech, impersonation, or targeted abuse.",
        "No spam, phishing, wallet drainers, malicious files, or deceptive links.",
        "Staff will never ask for a seed phrase, recovery phrase, private key, approval, transfer, or payment.",
        "Wallet verification uses a gas-free authentication signature only.",
        "Ignore unsolicited support DMs and trust only links published in official DYØØR channels.",
        "Follow Discord’s Terms of Service and Community Guidelines.",
      ],
    },
    waitingRoom: {
      title: "SYSTEM ACCESS GRANTED",
      body: "You are now DYOORyfied. This is the Waiting Room—the public hub for verified members of the DYØØR network. Sync one or more wallets below to unlock every holder channel you qualify for.",
    },
    security: {
      title: "DYØØR SECURITY PROTOCOL",
      body: "Staff will never request seed phrases, recovery phrases, private keys, approvals, transfers, or payments. Wallet verification costs zero gas and asks only for a short-lived authentication signature. No transaction is sent, and it never calls approve() or setApprovalForAll(). Ignore unsolicited support DMs.",
    },
  },
} as const satisfies ProjectConfig;
